version: '1.0'

services:
  db:
    container_name: db
    image: postgres:14.5-alpine3.16
    ports:
      - "5432:5432"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
      - ./backend/entrypoint:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root

  backend:
    container_name: asp_backend
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - DB_PORT=5432
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=root
      - DB_NAME=postgres
    depends_on:
      - db

  client:
    container_name: client
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client/src:/client/src'
      - './client/public:/client/public'
    ports:
      - "5001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  proxy:
    container_name: proxy
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
